### ISSUE TITLE
Issues with git precommit-hook, NPM

### ISSUE THREAD

**Issue by orangejulius** [pelias/api#1179]
For a long time we have noticed that our git [precommit-hook](https://www.npmjs.com/package/precommit-hook) setup has some issues. It is intended to ensure, among other things, that NPM packages are correct and up to date before allowing any commits. This prevents, for example, tests passing only with an old, or new, or missing NPM package.

In general, it works quite well, however sometimes it breaks when things are clearly right (for example a fresh `rm -rf node_modules; npm install` has just been run).

This seems to be related to things like optional dependencies of very deeply nested packages, in particular [tape](https://www.npmjs.com/package/tape)

Some known fixes:
- run `npm install` twice (yes, seriously)
- change the version of `tape` to 0.2.2 (see https://github.com/pelias/api/pull/1178)

This has been going on for years, across NPM versions, and is really annoying. I've taken a look at it a few times but never figured out the exact cause.

**Comment by worace** [comment]
I don't really have any answers yet but I put together a simple bash script to test this out on a few different versions (relies on having NVM set up):

```
#!/usr/bin/env/bash

versions="4.9.1 6.14.3 8.11.3 9.11.2 10.8.0"

cd ~/code/pelias/api

export NVM_DIR="$HOME/.nvm"
. $NVM_DIR/nvm.sh

for v in $versions; do
  echo "** NVM Version $v **"
  nvm install $v &> /dev/null
  nvm use $v

  rm -rf node_modules
  npm install &> /dev/null

  if npm ls > /dev/null; then
    echo "** Succeeds on $v **"
  else
    echo "** Fails on $v **"
  fi
done
```

For me it seems to consistently fail on `6.14.3` alone. Would be interesting to see if that is reproducible for others. I may be able to try it on another machine as well. Here is my output:

```
** NVM Version 4.9.1 **
Now using node v4.9.1 (npm v2.15.11)
** Succeeds on 4.9.1 **
** NVM Version 6.14.3 **
Now using node v6.14.3 (npm v3.10.10)
npm ERR! missing: tape@~0.2.2, required by zlib-browserify@0.0.3
** Fails on 6.14.3 **
** NVM Version 8.11.3 **
Now using node v8.11.3 (npm v5.6.0)
** Succeeds on 8.11.3 **
** NVM Version 9.11.2 **
Now using node v9.11.2 (npm v5.6.0)
** Succeeds on 9.11.2 **
** NVM Version 10.8.0 **
Now using node v10.8.0 (npm v6.2.0)
** Succeeds on 10.8.0 **
```

So far that matches the issues I was seeing with this the other day, specifically that it was failing on a conflict with `tape@~0.2.2`

As for why that's failing on only some Node/NPM versions, I'm not really sure.

[Here](https://github.com/brianloveswords/zlib-browserify/blob/master/package.json#L10) is the dependency that is being inherited for that, and [here](https://github.com/pelias/api/blob/master/package.json#L82) is pelias-api's conflicting one.

My understanding of NPM's version resolution approach is that it should in theory allow each of those dependencies to exist, one in the top-level and one nested underneath `zlib-browserify`:

```
$ cat node_modules/tape/package.json | jq .version
"4.9.1"
$ cat node_modules/iso3166-1/node_modules/zlib-browserify/node_modules/tape/package.json | jq .version
"0.2.2"
```

But for some reason under `6.14.3`, `zlib-browserify` seems to be appearing at the top level rather than nested under `iso3166-1`:

```
find . -name "zlib-browserify"
./node_modules/zlib-browserify
```

As is `tape`:

```
find . -name "tape"
./node_modules/tape
cat node_modules/tape/package.json | jq .version
"4.9.1"
``` 

So I guess it's possible there is some difference in how certain versions of NPM handle this scenario. I'd have to do more research to see if there are known issues around this.

It would be interesting to see if someone else is able to reproduce this reliably on that specific node/npm version, or if I'm just getting (un)lucky and it's not really version-related at all.

In terms of fixes, a couple approaches could be:

* Figure out what Node/NPM versions are bad and just avoid them. If lots of people are using NVM, this could be done with a [.nvmrc file](https://github.com/creationix/nvm#nvmrc)
* Pin the version to `0.2.2` to match what zlib-browserify requires. Although this feels a bit like giving in...

**Comment by orangejulius** [comment]
Damn this is some good research. I can confirm some of this from some much less comprehensive testing I've done. It does seem like it could be a bug in NPM, but that seems hard to get fixed or even prove. In any case, telling Pelias users to avoid certain versions of NPM is probably impractical. You are right that There is no way we are downgrading to a 0.x version of `tape` :)

Ultimately, the problem is that [zlib-browserify](https://github.com/brianloveswords/zlib-browserify)  has not seen a release in 5 years. I happen to know @brianloveswords and can maybe bribe him with cat pictures or something to do a release to upgrade to a modern version of tape. But would we always have to keep them in sync? That's also impractical.

`zlib-browserify` is a dependency of [iso3166-1](https://github.com/moimikey/iso3166-1), so we'd also have to push for a new release there.

However, I think the best solution is to switch to [iso-3166-1](https://github.com/ecrmnn/iso-3166-1) (yes, the only difference in the NPM package name is the hyphen). This package doesn't have any non-dev dependencies at all. And ultimately, keeping an up to date list of ISO-3166-1 codes is not exceedingly hard, so we could also avoid using an external module at all.

Either of those options would make for great PRs.

**Comment by worace** [comment]
That's a good suggestion, I didn't really think about just swapping the ISO package which is the parent of all of these. Seems like it shouldn't take too complex of a package to store some ISO string mappings.

FWIW I also got the issue on a different machine running Node 8.10 and NPM 2.15 without NVM, so I guess my earlier tests pointing to Node 6/NPM 3 are not totally conclusive:

```
$ node --version
v8.10.0
$ npm --version
2.15.8
$ npm ls > /dev/null
npm WARN unmet dependency /home/worace/code/pelias/api/node_modules/zlib-browserify requires tape@'~0.2.2' but will load
npm WARN unmet dependency /home/worace/code/pelias/api/node_modules/tape,
npm WARN unmet dependency which is version 4.9.1
npm ERR! invalid: tape@4.9.1 /home/worace/code/pelias/api/node_modules/tape
```

I also found this [relatively terse StackOverflow Issue](https://stackoverflow.com/questions/25696584/what-does-invalid-mean-when-using-npm-list/39330713) which suggests it may be due specifically to conflicting Dev vs Non-Dev dependencies.

I'd be down to take a look at either moving to that alternative ISO package or even just bringing it internal and ditching the library.

Somewhat tangential but I did a little bit of poking around and was surprised to see that both of these libraries seem to be doing a [linear](https://github.com/moimikey/iso3166-1/blob/master/src/index.js#L20) [search](https://github.com/ecrmnn/iso-3166-1/blob/master/src/index.js#L14) for ISO 2/3 matches which should presumably be a constant-time lookup in some mapping. I guess the first one is technically filtering through all possible matches and then returning the first one, so it's constant time...of searching through the whole array. The second one at least is polite enough to early exit if it finds a match, so you get stuff like this:


```
> const iso = require('iso-3166-1');
SyntaxError: Identifier 'iso' has already been declared
> console.time("isocheck");
undefined
>
> for(i = 1; i < 30000; i++){
...   iso.whereAlpha3("ZWE");
... }
{ country: 'Zimbabwe',
  alpha2: 'ZW',
  alpha3: 'ZWE',
  numeric: '716' }
> console.timeEnd("isocheck");
isocheck: 96.217ms
undefined
>
> const iso = require('iso-3166-1');
SyntaxError: Identifier 'iso' has already been declared
> console.time("isocheck");
undefined
>
> for(i = 1; i < 30000; i++){
...   iso.whereAlpha3("AFG");
... }
{ country: 'Afghanistan',
  alpha2: 'AF',
  alpha3: 'AFG',
  numeric: '004' }
> console.timeEnd("isocheck");
isocheck: 9.246ms
undefined
```

**Comment by orangejulius** [comment]
Yeah, bringing the definitions into this repo seems like the best move. I was initially concerned about duplication, since we used ISO-3166-1 codes in the whosonfirst importer as well, but I was able to remove those easily in https://github.com/pelias/whosonfirst/pull/374, so I think this is the only place left.

**Comment by orangejulius** [comment]
I believe this has been thoroughly fixed (thanks @worace!). If anyone else is still encountering issues, please let us know.
