### ISSUE TITLE
[discuss] uncaught errors killing the process

### ISSUE THREAD

**Issue by missinglink** [pelias/api#125]
With our current controller configuration there is potential for dodgy code nested deep inside async callbacks to throw Errors which miss all the synchronous `try/catch` blocks and make their way all the way up the stack to trigger `process.on('uncaughtException')` and promptly `exit(1)` the whole process.

This is obviously super-bad as all the connections get dropped, the API goes down on that box and the process has to be restarted, also the load balancers get affected et cetera, it's just bad.

At time of writing this has only happened once and it was only triggered in an extreme edge-case which wasn't covered by unit testing; however there is potential for some dodgy code from `us/them` one day causing us some serious problems.

This is a classic nodejs issue and there is only one way of dealing with it for good, firstly here are some 'bad' ways of dealing with it:

**[bad]** trying to catch async code (ie. the sound of one hand clapping)
```javascript
try{ setTimeout( function(){ throw new Error('catchme'); }, 1 ); }
catch( e ){}
// your process just crashed
```

**[bad]** wrapping all your sync code
```javascript
try{ chaosMonkey(); }
catch( e ){}

try{ chaosMonkey(); }
catch( e ){}

try{ chaosMonkey(); }
catch( e ){}
// your code is not pretty
```

**[bad]** using 'uncaughtException'
```javascript
process.on('uncaughtException', function(){
  console.log('I\'m ok; really');
});
throw new Error('catchme');
// your application state is unstable
```

**[bad]** hoping express will handle this for you
```javascript
app.get('/foo', function( req, res, next ){
  setTimeout( function(){ throw new Error('catchme'); }, 1 );
});
// your process just crashed
```

...not to be confused with:
```javascript
app.get('/foo', function( req, res, next ){
  next( new Error('catchme') );
});
// your process is ok
```

..so there is basically one option left; called [domains](https://nodejs.org/api/domain.html) which has a long history in the nodejs community and I've been told many times that its going to be deprecated and not to use it, however since there is no alternative, it remains in core. (maybe the old issues with it have been solved, I'm not sure)

There is a lengthy discussion over at `io.js` [1] which shows a nice way of implementing domains inside an express app and discusses some of the pros/cons of this approach.

[1] https://github.com/mikeal/nodeconf2013/issues/6#issuecomment-19092750

**Comment by orangejulius** [comment]
In the Ruby world, this is handled pretty elegantly if you are using something like Unicorn. Unicorn runs a bunch of processes that were all forked from a master process that manages them all. If any one of them fails, the master can spawn a new one and because they use Unix magic to share a TCP port, nothing outside the webserver experiences any disruption (except of course the one failed request). 

I tried to find a Unicorn-like thing for Node.js and only got a few extremely old and dead github projects, warnings that a Unicorn-like way of thinking is terribly terribly bad in the Node.js world, and an explicit request for best practices solving this problem that quickly became an [existentiallist](http://grokbase.com/t/gg/nodejs/13becd3kwp/whats-the-unicorn-for-node-how-should-i-think-of-deployment) discussion arguing against the very existence of best practices.

**Comment by orangejulius** [comment]
We currently use [runit](https://en.wikipedia.org/wiki/Runit) in production, and haven't noticed any problems, so I think we can close this.
