### ISSUE TITLE
Phrase queries in Elasticsearch 6

### ISSUE THREAD

**Issue by nickpeihl** [pelias/api#1261]
Hey all. I wanted to reach out about your efforts to migrate to [Elasticsearch 6](https://github.com/pelias/pelias/issues/719). I'm very interested in helping out. 

Many of the phrase queries in the unit test fixtures of pelias/api fail because the match queries have a [`type: 'phrase'`](https://github.com/pelias/api/blob/master/test/unit/fixture/autocomplete_boundary_country.js#L13) parameter that is no longer supported in Elasticsearch 6+. This has been replaced by the `match_phrase` query type.

The [`match_phrase` query type](https://www.elastic.co/guide/en/elasticsearch/reference/6.6/query-dsl-match-query-phrase.html) does not support `cutoff_frequency` and `operator` parameters. However, these parameters are still supported in the [`match` query type](https://www.elastic.co/guide/en/elasticsearch/reference/6.6/query-dsl-match-query.html). The `match` query type no longer supports `slop`. 

For an example, let's look at https://github.com/pelias/api/blob/master/test/unit/fixture/autocomplete_boundary_country.js. There are two possible ways to make it compatibile with ES 6.

1)
```diff
diff --git a/test/unit/fixture/autocomplete_boundary_country.js b/test/unit/fixture/autocomplete_boundary_country.js
index 5da3698..2ad0df6 100644
--- a/test/unit/fixture/autocomplete_boundary_country.js
+++ b/test/unit/fixture/autocomplete_boundary_country.js
@@ -3,16 +3,14 @@ module.exports = {
     'bool': {
       'must': [{
         'constant_score': {
-          'query': {
+          'filter': {
             'match': {
               'name.default': {
                 'analyzer': 'peliasQueryPartialToken',
                 'boost': 100,
                 'query': 'test',
                 'cutoff_frequency': 0.01,
-                'type': 'phrase',
-                'operator': 'and',
-                'slop': 3
+                'operator': 'and'
               }
             }
           }
```

2)
```diff
diff --git a/test/unit/fixture/autocomplete_boundary_country.js b/test/unit/fixture/autocomplete_boundary_country.js
index 5da3698..6b1e87e 100644
--- a/test/unit/fixture/autocomplete_boundary_country.js
+++ b/test/unit/fixture/autocomplete_boundary_country.js
@@ -3,15 +3,12 @@ module.exports = {
     'bool': {
       'must': [{
         'constant_score': {
-          'query': {
-            'match': {
+          'filter': {
+            'match_phrase': {
               'name.default': {
                 'analyzer': 'peliasQueryPartialToken',
                 'boost': 100,
                 'query': 'test',
-                'cutoff_frequency': 0.01,
-                'type': 'phrase',
-                'operator': 'and',
                 'slop': 3
               }
             }

```

I'm not sure which is the preferred solution. So I'm reaching out for your thoughts.

**Comment by orangejulius** [comment]
Hi @nickpeihl,
Thanks for opening this issue and our follow up discussion we had offline after it.

I've been looking into query performance in general over the last few days and have also been thinking about this issue.

We use `cutoff_frequency` as a performance enhancement for queries that might match lots of documents, however it only can do that for queries with `operator: 'or'`. An `operator: 'and'` query is already about as efficient as it can be. Since every `phrase` query is necessarily (as far as I understand), already essentially using `operator: 'and'` (in a phrase query, all tokens in the input must match and be at a position compatible with the phrase matching), then we can drop the use of cutoff_frequency when we're using it with a `phrase` query. It's already having no effect even in ES5 or ES2.

Additionally, I'm not sure why that section of the query is using a `constant_score` clause, but we can probably drop that too. More investigation is needed there though.

**Comment by nickpeihl** [comment]
Thanks for the feedback. I haven't looked at this in a while, but I think my changes in this branch align pretty closely with what you have discovered. 

https://github.com/nickpeihl/api/tree/es6

**Comment by orangejulius** [comment]
Thanks for the help with this @nickpeihl! As you saw we fixed this in https://github.com/pelias/api/pull/1354 and now have ES6 compatibility nearly done :)
