### ISSUE TITLE
Autocomplete should prioritize exact matches

### ISSUE THREAD

**Issue by mihneadb** [pelias/api#1295]
In Bucharest, Romania, there are several universities. Most are called "University <something> of Bucharest", but one is simply "University of Bucharest", and there is also a metro station simply called "University" there.

Performing a search query for "University" ("Universitate" in Romanian) yields the expected result.
https://pelias.github.io/compare/#/v1/search%3Ffocus.point.lat=44.4378&focus.point.lon=26.0245&text=universitate

Performing an autocomplete query with the same params yields different results.
https://pelias.github.io/compare/#/v1/autocomplete%3Ffocus.point.lat=44.4378&focus.point.lon=26.0245&text=universitate

It looks like `autocomplete` prefers to match a prefix but somehow does not score more on exact matches. I would argue that `autocomplete` should prefer an exact result when available.

**Comment by orangejulius** [comment]
Hi! Sorry we never replied to this one. Partially it's because there's no easy solution :)

In general, Autocomplete can't prioritize exact matches. There are so many places that there will almost always be a poor but exact match. The classic example is searching for London: Lo, Lon, Lond, and Londo are all the names of places or at least an exact match for a word in a place's name.

I think the solution here is to improve our prioritization of results based on something that can help determine importance. The result you expect is a transit stop, which is generally of high importance. 

With that in mind I think this will be helped by efforts like https://github.com/pelias/openstreetmap/pull/493 which will improve popularity rankings based on OSM tags.

**Comment by mihneadb** [comment]
That makes sense, indeed. Maybe another heuristic could be the length of the input, i.e. if you typed more than 8 characters exact matches should rank higher.
I'll follow along, thanks!
