### ISSUE TITLE
geojsonify throws a TypeError due to undefined values

### ISSUE THREAD

**Issue by stevelacy** [pelias/api#1379]
If a provided id does not contain two or more `:` characters the value returned from the `decodeGID` function is undefined, and causes a TypeError to be thrown.

https://github.com/pelias/api/blob/f2af6663004ae335223fea3fefcc281f3f42c67b/helper/decode_gid.js#L10

https://github.com/pelias/api/blob/f2af6663004ae335223fea3fefcc281f3f42c67b/helper/geojsonify.js#L47

The change to use the decoded string was created in c867946b342cbe6d2cc36ed076d7a1c89977993c
```
Error: `TypeError: Cannot read property 'id' of undefined
at geojsonifyPlace (/home/pelias/helper/geojsonify.js:47)
at Array.map (<anonymous>)
at geojsonifyPlaces (/home/pelias/helper/geojsonify.js:23)
at convertToGeocodeJSON (/home/pelias/middleware/geocodeJSON.js:81)
at middleware (/home/pelias/middleware/geocodeJSON.js:21)
at geojsonifyPlace (/home/pelias/helper/geojsonify.js:47)
at Array.map (<anonymous>)
at geojsonifyPlaces (/home/pelias/helper/geojsonify.js:23)
at convertToGeocodeJSON (/home/pelias/middleware/geocodeJSON.js:81)
at middleware (/home/pelias/middleware/geocodeJSON.js:21)
```

**Comment by orangejulius** [comment]
Hi @stevelacy,
Thanks for reporting this. So as I understand it, this requires that a document in Elasticsearch has a value in the `_id` field that doesn't correspond to our GID structure, right?

All our importers should correctly manage this, so its hopefully not a common case. Do you know how it happened for you?

We'd still want to protect against this of course.

**Comment by stevelacy** [comment]
We just started seeing this after we updated to latest on master from an earlier release. I don't have an example of the document yet, is there a query to find one on ES?

**Comment by orangejulius** [comment]
Ah I see. In that case you've been hit by a breaking change we made several months ago.

You'll have to stay on versions of the API before [3.86.0](https://github.com/pelias/api/releases/tag/v3.86.0) until you can run a new Elasticsearch code with the latest importer code.

The importers will write to the `_id` field in the correct format since around August 30th (when they brought in [this](https://github.com/pelias/model/pull/121) change).

**Comment by stevelacy** [comment]
Gotcha, I pinned to `master-2019-10-03-58fbf6fa7633ca3faa4a6d44ae6405bb0503adf5` for now.

**Comment by orangejulius** [comment]
That will work.

For the record, version 3.86.0 should really have been version 4.0.0 to indicate a breaking change. Sorry about the confusion!

**Comment by stevelacy** [comment]
Do you want to announce the breaking change on the readme or changelog? I can close this issue otherwise

**Comment by missinglink** [comment]
The changelog is automatically generated from commit messages, I'll see if we can add it somewhere.

The project is over 5 years old now we sometimes need to change things to improve them, below is a little explanation of how we're handling those changes for anyone curious.

How it currently works in general (and in this case specifically) is that we split the feature up in to two or more merges, we put in the code to add future support first then we wait some time (usually about a month) to remove backwards compatibility.

It's actually a bit of work on our end but worth it to avoid incompatibility issues like this.

Unfortunately in your case the amount of time between when you built the index and the date on the API code was too large and so that window of interoperability was exceeded :(

A more robust solution might be for the API to check for index version compatibility at startup, although in this case it would simply terminate execution upon startup, this is still preferable to runtime errors.

We're currently working on support for Elasticsearch 6 which will come out very soon (we're currently on 5), this change will drop support for Elasticsearch 2.

That's not a big deal but we're planning on moving up to the latest Elasticsearch version (7) in early 2020, at this time we will drop support for 5 and I suspect that similar problems such as this might arise.

I'd strongly suggest everyone pin their versions in a production environment, all the code is published in datestamped immutable docker containers which makes this a breeze.

For dev environments our recommendation is to rebuild often and running a suite of acceptance tests which test all parts of the system before promoting a build to production.

**Comment by orangejulius** [comment]
Okay, I pushed https://github.com/pelias/api/pull/1382 which doesn't change anything but puts the breaking change in our release notes and bumps the API version appropriately.

It turns out all this was because of an extra underscore in the commit message for https://github.com/pelias/api/pull/1363/commits/863d68394647d7a8d4bd1966c5b10e2eddafc6c0 (the correct string to include in the commit message body to trigger a breaking change is `BREAKING CHANGE:` not `BREAKING_CHANGE:`).

Hopefully this issue and that release are enough to get anyone going again. If not, feel free to comment here or reopen this issue.
