### ISSUE TITLE
Problem with autocomplete method and compound names

### ISSUE THREAD

**Issue by pmperez-larioja** [pelias/api#1546]
Hi there!, we are working on a national project in which we collaborate with different official bodies (Spanish National Geographic Institute, Correos, Spanish Stadistical Office,…). We are implementing a national level geocoder with the official addresses of Spain. We have some problems with the autocomplete method, that sometimes doesn´t returns results.

Our Pelias API hosts is the following: https://geocoder-5-ign.larioja.org/

Using the Pelias Compare Tool; https://pelias.github.io/compare/#/v1/autocomplete?layers=address%2Cstreet%2Cvenue&text=calle+san+juan+5&debug=1

We get result when we don't put the street number, but when we add the street number, we don't get any record.

With the 'search' method we do get results.

![screencapture-pelias-github-io-compare-2021-07-21-10_49_00](https://user-images.githubusercontent.com/34767047/126460893-8de7ba20-25d4-4a74-b4c2-7590169d2257.png)
![screencapture-pelias-github-io-compare-2021-07-21-10_46_40](https://user-images.githubusercontent.com/34767047/126460904-d6ba2eb2-8135-4869-840a-6ef309640362.png)

I can send you our settings and mapping documents, perhaps you can help us with the problem.

Thanks a lot!!!

**Comment by missinglink** [comment]
Hi @pmperez-larioja, I had a look at the compare app for the `geocode.earth` servers and they seem to be returning the correct results:

https://pelias.github.io/compare/#/v1/autocomplete?boundary.country=ESP&layers=address%2Cstreet%2Cvenue&text=calle+san+juan+5

<img width="1417" alt="Screenshot 2021-07-22 at 10 44 51" src="https://user-images.githubusercontent.com/738069/126612290-1c37b5cf-ead2-4b6a-8083-49e58d3f9422.png">

This leads me to think that the problem is in your customisation of the code or data. I also noticed that in your screenshot some of the addresses are all capitals, which is uncommon in the 'stock standard' Pelias install.

We don't have the time to provide individual support for custom installs, they require a lot of review of the configuration and deployment which is far beyond the scope of the free support we offer for our open-source software.

**Comment by missinglink** [comment]
In the issue title you mention that the problem is related to 'compound names', could you please explain a little more about that?

We might be using that term differently? I usually thing of something like "straßenbahnhaltestelle" or "stadtbibliothek" as compound names since they concatenate several words into one. ie. 'compound' them.

**Comment by pmperez-larioja** [comment]
Thank you very much @missinglink for the hint you have given us, we have found a solution to our problem by filling in the fields as follows:
filling the phrase.default and name.default field with address_parts.number + address_parts_street

Thus, for a compound street (with more than one word), 'Calle San Juan 5', we store it as '5 Calle San Juan'.
Thus we obtain the desired results.

Thank you very much!
