### ISSUE TITLE
[discuss] geo_distance tuning

### ISSUE THREAD

**Issue by missinglink** [pelias/api#157]
I merged https://github.com/pelias/api/pull/156 super fast and then @hkrishna posed some good questions about it, so let's continue the discussion here and maybe loop in @riordan too.

I landed this change earlier https://github.com/geopipes/elasticsearch-backend/pull/7 which is aimed at fixing the semi-broken implementation we have for `/search` when using a `lat/lon` bias.

For clarity, we have 3x different queries which can take a `lat/lon` input in order to filter and sort results better:

[1] `/search` with `?lat=` and `?lon=`
[2] `/reverse` with no categories specified (lat/lon is mantatory)
[3] `/reverse` with categories specified (lat/lon is mantatory)

There are 2x different options of what effect the `lat/lon` has on the query.

[R] it can **filter** the results returned to ONLY those which lie in a certain radius of the point
[S] it can **sort** the results by their distance from the point, closest first.

For [1], we previously did [R] at '50km' and we also did [S] which was wrong.
Today I removed [S] and left [R] at the default of '50km'

For [2] and [3] I made sure [S] was still enabled and changed [R] to '500km' which may be wrong?

The question is, what are the correct values for the radius for each [1], [2] and [3]?

**Comment by hkrishna** [comment]
I think [1] could have a large radius but should be sorted from the lat/lon provided or else it will be equivalent to a bbox search query, right?

[2] shouldnt have a large radius because that just basic reverse lookup - if there is nothing around a lat/lon then it shouldnt return any results

As for [3] it could go either way because now you are searching for a specific category - this is not a reverse lookup, I consider this a search based on category (find all chinese restaurants around a given lat/lon) .. in fact, I'd go as far as making this a different end point.. ```/find```?

**Comment by missinglink** [comment]
all good points

re: [1] I have changed my view on this, the question is should it:
a) filter on linguistics and sort on distance?
b) filter on distance and linguistics and sort on a variety of criteria?

Which is the expected behaviour for most users? I know there was some analysis of pelias recently where they expected [1] to do [b] but instead it did [a]

[2] I agree that we should probably not return results from more than say 50km for a traditional reverse geocoding result. In 99.9% this setting won't really matter, especially when only returning a single result, at the max of 40 results its only relevant in areas where the data is sparse.

[3] is kind of like [1], it would be nice to have a bunch of nearby chinese restaurants, but also should probably not return those over say 200km away

**Comment by dianashk** [comment]
- __[1]__ I would expect [S] to behave as described in [b], so that the thing matching what I asked for in the input shows up first, even if further away. Can we add a parameter like `radius` to allow users to override the default distance?

 - __[2]__ For regular [R] queries, 50km is probably just fine, as we want to do our best to return something really really close to the query location.

 - __[3]__ I agree with @hkrishna on this being conceptually different from `/reverse`. In fact, I'd argue that we should not support `categories` in reverse as you can accomplish the same results using something like...

> `/search&categories=food&lat=123&lon=321&radius=100`

> (where `radius` is overriding the default 500km)
