### ISSUE TITLE
pelias - postalcode structure geocoding is not working/no response

### ISSUE THREAD

**Issue by MALKARAJ** [pelias/api#1682]
Hi Team,
postalcode search doesn't show response for the some of the request

this is the autocomple search result for /v1/autocomplete?size=40&text=kolkata
![postalcode-700031](https://github.com/user-attachments/assets/fdb3c196-c63f-4f53-80e9-5096c160154d)

when search using /v1/search/structured?size=25&postalcode=700031 it doesn't show any response
<img width="1429" alt=":v1:search:stru-postalcode" src="https://github.com/user-attachments/assets/e8cd7429-927b-4c2c-aea2-32486d2e036a" />

**Comment by missinglink** [comment]
Hi @MALKARAJ 

The reason is that postcodes have two forms in Pelias.

In the first screenshot you're seeing an *attribute of an address*, this is text someone has added to that specific hospital in OpenStreetMap.

Many places may have the text '70031' in the postalcode field, both in India and abroad.

In your second query you're doing a *reverse* search, now this *could* do one of two things:
1. Return a single feature representing the postcode 70031
2. Return all the places in the index where the postal field contains 70031.

We do the 1. which sometimes confuses people, the reason is that enumerating all the places with a specific postcode is not generally very useful and is better suited to a database than a search engine, you can use something like OverpassTurbo if that is your goal.

The reason you're not seeing a result on the GeocodeEarth production server but you are on the dev server is that we're currently working on resolving this issue in India by adding postcode centroid from India Post.

Once [this issue is resolved](https://github.com/whosonfirst-data/whosonfirst-data/issues/2218#issuecomment-2405345065) you'll see a single result like what's shown on the dev server (right column).

GeocodeEarth customers will likely see this feature earlier.
