### ISSUE TITLE
`/search?source' parameter enables scoping of search by origin of source data

### ISSUE THREAD

**Issue by riordan** [pelias/api#181]
A user should be able to scope their search by the source of the data.

For instance:

`GET <pelias>/search?text=123 Broadway, NYC&source=openstreetmap`

should only return valid matches from OpenStreetMap, and not OpenAddresses.

This is fundamentally different from Layers, because while Layers may refer to parts of a dataset or even the whole dataset (e.g. OSMWays + OSMnodes), Source only reflects the provenance of that dataset.

**Comment by riordan** [comment]
I suspect this will have implications on the importer pipeline with each importer needing to include a `source` for each document.

cc: @missinglink

**Comment by riordan** [comment]
What do folks think of a programatic way to list all the valid targets for a `source'?

I suspect this approach could also apply to categories (pelias/api#174).

**Comment by riordan** [comment]
Not reindexing at this time. Provide aliasing for OSM, Geonames, OpenAddresses

**Comment by orangejulius** [comment]
So, for V1, we aren't going to reindex yet. This means we have to "fake" a source field using the type field. Currently, the following values can exist for type:

    'geoname',
    'osmnode',
    'osmway',
    'admin0',
    'admin1',
    'admin2',
    'neighborhood',
    'locality',
    'local_admin',
    'osmaddress',
    'openaddresses'

The layer api field can contain any type value, or one of the 3 following aliases, which expand into several types: 

    'poi', ['geoname','osmnode','osmway']
    'admin', ['admin0','admin1','admin2','neighborhood','locality','local_admin']
    'address': ['osmaddress','openaddresses']

A mapping from source to type would look something like this:

    'geonames': ['geoname'],
    'openaddresses' : ['openaddresses'],
    'quattroshapes': ['admin0', 'admin1', 'admin2', 'neighborhood', 'locality', 'local_admin'],
    'openstreetmap' : ['osmaddress', 'osmnode', 'osmway']

Since there's only one field, we will be setting a list of allowable types in the actual Elasticsearch query based on the source field and the layers field, which raises the question of what to do when both are specified. There's 3 ways it could be done:

1.) ignore layer when source is present
2.) ignore source when layer is present
3.) only query for types that satisfy both the layer and source queries

Option 1 and 2 have the advantage that the number of types searched will always be non-zero, but the disadvantage is they require ignoring user input, so the query doesn't really do what it says it will. Option 3 on the other hand, would essentially have the code trying very hard to do what the user has asked, even if doesn't really make sense, or wouldn't return any results. For example:

    /v1/search?layer=address&source=geonames

Option 1 would return geoname results only
Option 2 would return osmaddress and openaddress results only
Option 3 would return nothing

I'm still in favor of option 3, for a couple reasons:
1.) It does exactly what the request says, even if there aren't going to be results returned
2.) It works exactly the same as if we were filtering on the layers field as it exists today, as well as independently filtering on a source field that we want to create in the future
3.) It only fails to return results in cases that exist with our current data sources, as they exist today. We could easily add more data sources in the future with different combination of types of data, and then more combinations of layer and source would return results.
