### ISSUE TITLE
Introduce '/search?extent.radius' to enable configuring distance around an extent.lat/extent.lon

### ISSUE THREAD

**Issue by riordan** [pelias/api#184]
When an API user provides a latitude or longitude to center a search around, the API user should be able to control the extent of the search around that point. Today, we hard code the maximum search distance to as 500km (previously 50km see pelias/api#157), but that distance should be user configurable.

When an API user provides an `extent.lat extent.lon` pair to a search query, she may also optionally provide a `radius` parameter, a string specifying the distance from that latitude/longitude to search.

Should accept distance in multiple formats:
- meters 'm'
- kilometers 'km'
- miles 'mi'

Defaults to 50000m.

**Comment by riordan** [comment]
Should we also offer this as a parameter for a bounding box, expanding the distance beyond the bbox? Is that even geometrically valid?

**Comment by hkrishna** [comment]
```extent.radius``` wont make sense for bounding box because a bounding box by definition is an enclosed area. If we allow radius to play with bbox (lets call this bbox1) param - then we'll find ourselves doing things like finding the centroid of the bounding box and then calculating another area (lets call it bbox2) with the given radius from the centroid - what if bbox2 is smaller than bbox1 or vice versa - how does that affect sorting order of the results? 

I dont think its worth the effort. I think adding ```extents.radius``` to  ```lat/lon``` is an elegant way of describing a geographic filter.

**Comment by hkrishna** [comment]
I think we should be able to support more formats. Here's a list
```yaml
Mile 'mi'
Yard 'yd'
Feet 'ft'
Inch 'in'
Kilometer 'km'
Meter 'm'
Centimeter 'cm'
Millimeter 'mm'
Nautical mile 'nmi'
```
As per https://www.elastic.co/guide/en/elasticsearch/reference/1.6/common-options.html#distance-units

**Comment by riordan** [comment]
Been some discussion between myself and @missinglink about whether radius makes sense or just to have users construct a bounding box. At this time (supporting Erasermap principally) it seems to make sense to not use radius, but instead to let them use a bounding box to set that search area.

We could then add that helper function in for more traditional-geocoding type API.

Thoughts?
