### ISSUE TITLE
Add content for `attribution` and `license` static endpoints

### ISSUE THREAD

**Issue by dianashk** [pelias/api#212]
Geocoding block contains info about `attribution` and `license` which need content.

Once content is prepared, the endpoints need to be added to the routing.

**Comment by riordan** [comment]
# Background
While OSM does let us include links, their required form of crediting is: <quote>© OpenStreetMap contributors</quote> with links to the [ODbL](http://opendatacommons.org/licenses/odbl/1.0/) and [OSM Copyright page](http://www.openstreetmap.org/copyright).

So while license is a field which we have ing GeocodeJSON that we had intended to be an array of strings of URLs for licenses, that doesn't provide a single governing license for the response document, and the OSM license is actually 2 links because ugh.

We get around this for the time being by using ONLY `attribution` and sending a single attribution message with all our responses (for now. I have it on my agenda to follow up with our lawyers to get to a simpler system).

@nvkelso & I have been tossing some possibilities around, and owing to the need to link-ify many of the data sources (particularly OSM + Quattroshapes
<quote>"Attribution" : "Geocoding by Pelias from Mapzen. Data from OpenStreetMap[http://www.openstreetmap.org/copyright]  © OpenStreetMap contributors under ODbL[http://opendatacommons.org/licenses/odbl/], Quattroshapes[https://github.com/foursquare/quattroshapes/blob/master/LICENSE.md] under CC-BY-2.0, GeoNames[http://www.geonames.org/] under CC-BY-3.0, and other sources."</quote>

It's not pretty. But it's accurate. And meets the attribution requirements of the governing licenses.

We [do the same](https://github.com/whosonfirst/whosonfirst-data/blob/master/LICENSE.md) with Who's on First and had to go through some hoop jumping to make it work.

We should do our best to display content under ideal circumstances in attribution, where there is the ability to display HTML or not.

# Actual Content
**/attribution**
```
{
attribution_general: 'Geocoding by Pelias from Mapzen. Data from OpenStreetMap[http://www.openstreetmap.org/copyright]  © OpenStreetMap contributors under ODbL[http://opendatacommons.org/licenses/odbl/], Quattroshapes[https://github.com/foursquare/quattroshapes/blob/master/LICENSE.md] under CC-BY-2.0, GeoNames[http://www.geonames.org/] under CC-BY-3.0, and other sources.',

attribution_html: 'Geocoding by <a href="https://mapzen.com/pelias">Pelias</a> from <a href="https://mapzen.com">Mapzen</a>. Data from <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>  © OpenStreetMap contributors under <a href="http://opendatacommons.org/licenses/odbl/">ODbL</a>, <a href="https://github.com/foursquare/quattroshapes/blob/master/LICENSE.md">Quattroshapes</a> under <a href="https://creativecommons.org/licenses/by/2.0/">CC-BY-2.0</a>, <a href="http://www.geonames.org/">GeoNames</a> under <a href="https://creativecommons.org/licenses/by/2.0/">CC-BY-3.0</a>, and other sources.'
}
```
___
Additionally, to clear up which data sources are which in the records, we should name the sources in the documents so that they are explicit and not abbreviations.

- `gn` becomes `Geonames`
- `qs` becomes `Quattroshapes`
- `osm` becomes `Openstreetmap`


Admittedly, this assumes a single license/governing terms per source, which may not be the case in the future.

**Comment by dianashk** [comment]
@riordan I think we're missing OpenAddresses in the attribution text.
