### ISSUE TITLE
Should warn if any unexpected parameters are found in query.

### ISSUE THREAD

**Issue by missinglink** [pelias/api#279]
# error when specifying singular of 'sources' or 'layers'

I frequently make the mistake of setting 'source' instead 'sources'; same for 'layer', the API responds without a warnings or errors which causes me much confusion until I catch my typo.

We should at very least `warn`, but ideally `error` in this case so we `fail fast, fail early`

**Comment by dianashk** [comment]
Should warn if any unexpected parameters are found in query.

**Comment by orangejulius** [comment]
This issue has cropped up several times in the past few months, and it really feels like we should prioritize it for the near future. I believe we should first warn, and then perhaps a few weeks later error on any unknown parameters.

## How do unexpected parameters cause problems

In addition to the general case @missinglink mentioned where parameters are not quite correct, there are two additional problems specifically for Mapzen Search.

If a user intends to send along the `api_key` parameter, but instead uses `apikey`, `apiKey` or another similar but unknown parameter, they will fall back to the keyless rate limit, which is currently very low. It's pretty hard to trace down this issue.

Another problem we've seen is users sending along parameters that don't actually exist, but were presumably passed along from one of their internal APIs. For example someone might send along a "session_id" or "user_id" parameter. This doesn't change the results, but it does cause them to lose any benefits of caching. It increases the load on Mapzen Search and also prevents that user from getting "free" requests that were already cached.

## How should we implement this?

Right now there's no central place in any of our code that actually knows what all the parameters the API accepts are. We obviously have lists in our documentation, but that's really the only place.

A big concern about the implementation is that if the list of "acceptable" parameters gets out of sync with what parameters are actually allowed, bad things will happen. It would also be annoying and error-prone to have to maintain this list somewhere. Therefore it feels like the implementation for parameter verification _must_ involve building a way for the API to know what parameters are possibly used.

I wonder if we could build this into our sanitizers. Right now, sanitizers are passed the entire `raw` query object. If they were made so that they had to register ahead of time which parameters they used, then the code that currently runs all the sanitizers would have the full list of parameters, and could use that to validate all the params.

**Comment by tigerlily-he** [comment]
Will unexpected properties in `raw` get sanitized and passed onto `clean`? (ie. `clean['layer'] = raw['layer']`) 

If so, would it be sufficient to check that every property in `raw` is also in `clean`? Any property from `raw` that is not found in `clean` would be an unexpected parameter. This way, there is no need to create a list of acceptable parameters to check against. This sanitizer can run after all other sanitizers.
