### ISSUE TITLE
Soft focus not working as expected

### ISSUE THREAD

**Issue by dianashk** [pelias/api#287]
The following query used to work and started failing with the introduction of the soft focus:

[try it](http://search.bigdev.com/v1/autocomplete?text=didi&focus.point.lat=40.744243&focus.point.lon=-73.990342)

The focus point is in NYC and you can see the expected result when searching for `DiDi Dump`. It's less than a kilometer away from the focus point.

- [x] Issue Resolved
- [ ] Tests

**Comment by missinglink** [comment]
hmmm.. so the soft focus *is* working, it's just not as strong as you might have liked, if you try `/v1/autocomplete?focus.point.lat=40.744243&focus.point.lon=-73.990342&text=didi dumpling` you can see that it is returned when fully specified, for the query `/v1/autocomplete?focus.point.lat=40.744243&focus.point.lon=-73.990342&text=didi` there is no real way of telling that the dumpling place is what you are looking for, there are 10+ places in the world called 'Didi' and so they are being returned because they are a perfect linguistic match.

if we changed the balance to boost local results higher we might get to a point where it is impossible to find far away places by exact name because they are pushed further down the list by all the local results.

**Comment by riordan** [comment]
This is pretty good now. Just needs a test.

**Comment by missinglink** [comment]
this is much better now:

```
/v1/autocomplete?focus.point.lat=40.744243&focus.point.lon=-73.990342&text=didi

 1)	Didier, Bethlehem, PA, USA
 2)	DiDi Dumpling, Manhattan, NY, USA
 3)	Didim, Aydin, Turkey
```

**Comment by missinglink** [comment]
resolved by https://github.com/pelias/acceptance-tests/pull/197
