### ISSUE TITLE
Is there a "layer" for postcodes/ZIP codes?

### ISSUE THREAD

**Issue by stevevance** [pelias/api#312]
I believe that postcodes and ZIP codes are not open source boundaries in some jurisdictions, but are they searchable in Pelias?

**Comment by riordan** [comment]
Not at this time. Our data team is looking into how we might be able to
augment the data for postcodes (from beyond extracting them from addresses).

Also Zip Codes are weird, in that they're actually postal routes, not
boundaries.

On Fri, Sep 25, 2015 at 2:06 PM, Steven Vance <notifications@github.com>
wrote:

> I believe that postcodes and ZIP codes are not open source boundaries in
> some jurisdictions, but are they searchable in Pelias?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pelias/api/issues/312>.
>



-- 
David Riordan | Product Manager - Search | dave.riordan@mapzen.com |
@riordan <https://twitter.com/riordan> | gpg 235D9DC95EF6277C
<https://keybase.io/riordan>
Mapzen | https://mapzen.com | @mapzen <https://twitter.com/search>

**Comment by missinglink** [comment]
The `/v1/search` endpoint will try to match postcode data from fully specified address inputs.

You can test this out by sending a fully specified address and then looking in the meta data of the response object. If the address parser produces something like `parsed.postalcode` then we will attempt to match that against postcode fields where we have them.

At this time address parsing is disabled for `/v1/autocomplete`

The issue is that the postcode data is not amazing and we are always looking for how to improve that, I also have a post it note on my monitor to fix that analysis to account for spaces and oddness in the postcodes themselves.

**Comment by stevevance** [comment]
Thanks. 

@riordan I know - it's odd. Do other countries do it like the United States Postal Service?

**Comment by missinglink** [comment]
ref: https://github.com/pelias/schema/pull/77

**Comment by riordan** [comment]
blast from the past!

@stevevance I don't know of any other countries that treat their postal codes as linear routes, but that doesn't mean they don't exist. I imagine systems like UK Postcodes with small, targeted areas, but they're not routes, per se.
