### ISSUE TITLE
Add Coarse Autocomplete Search

### ISSUE THREAD

**Issue by riordan** [pelias/api#337]
The users have spoken and they want autocomplete for cities and regions (e.g. Mapillary home page).

Lets bring it back.

**Comment by missinglink** [comment]
what is the problem exactly?

![1](https://cloud.githubusercontent.com/assets/738069/10454325/227c9b90-71b4-11e5-8021-816f6b658538.jpg)
![2](https://cloud.githubusercontent.com/assets/738069/10454327/241781e0-71b4-11e5-8afb-d30526597bb1.jpg)

**Comment by missinglink** [comment]
oh, I think I figure out what this ticket is about, you mean adding `/autocomplete?layers=coarse`, `/autocomplete/coarse` or similar?

It would be awesome if `/autocomplete` "just works", as per the conversation going on here https://github.com/pelias/pelias/issues/143

in that case we wouldn't need a `/autocomplete/course` endpoint.

if we do decided to go down this route I would suggest `/autocomplete/course` over `/autocomplete?layers=x` because the latter is a cache killer

**Comment by riordan** [comment]
This pairs nicely with WOF-based boundaries for autocomplete (#373)

**Comment by missinglink** [comment]
closing in favour of:
- https://github.com/pelias/api/issues/449
- https://github.com/pelias/api/issues/373

this ticket also mentions using a new endpoint `/autocomplete/course` which is worth considering.
