### ISSUE TITLE
low confidence score

### ISSUE THREAD

**Issue by missinglink** [pelias/api#342]
hey @dianashk when I was looking at another issue I noticed the result in https://github.com/pelias/pelias/issues/141#issuecomment-146583343 has a pretty low confidence score for a very good linguistic match.

any idea what's going on here?

**Comment by orangejulius** [comment]
It looks like this happens when size=1. See [size=1 query](http://pelias.github.io/compare/#/v1/search%3Fsize=1&text=7%20Kurf%C3%BCrstenstrasse,%20berlin,%20germany) vs [size=10 query](pelias.github.io/compare/#/v1/search%3Fsize=10&text=7 Kurfürstenstrasse, berlin, germany). But yeah, why does this happen? hmmm

**Comment by dianashk** [comment]
I believe this has been fixed. Both size=1 and size=10 now return confidence of 1 and say they are an exact match.
