### ISSUE TITLE
Display only unit test failures

### ISSUE THREAD

**Issue by orangejulius** [pelias/api#343]
Currently when we run our unit tests, there is output for all (currently) 840 tests. This means when a few tests are failing, one normally has to scroll super far up to view the failure. Alternatively some of us comment out lines in the `test/unit/run.js` file, which isn't ideal either.

Many test suites only display output for failing tests, and there are quite a few ways to do that with tape/TAP. There's a list of TAP parsers that do this. Unfortunately [tap-spec](https://github.com/scottcorgan/tap-spec), the one we're using, doesn't.

Looking at the [list](https://github.com/substack/tape#pretty-reporters) on the tape readme, the one I like the most so far is [tap-dot](https://github.com/scottcorgan/tap-dot).

**Comment by missinglink** [comment]
I would be :+1: for refactoring how our test suites run. We discussed in the past pros/cons of different testing frameworks and I think the value of `tape` is that it's simple and compose-able, so let's change it up!

Totally agree that scrolling all the way up to find the failing test case is super annoying, the other major annoyance is when 2 different json files have a minor difference and I spend like 10 minutes trying to figure out what this is exactly.

I started a new personal project recently and decided to get rid of `run.js` which is also annoying, because you have to add new cases in there all the time and basically hand-hold it to do the right thing.

In the end I just created a new module called `testing` and in it are 2x files:

- `runner.js`
```
"use strict";

let tape = require('tape'),
    requireGlob = require('require-glob'),
    pattern = process.argv[2]

let files = requireGlob.sync('**/*Test.js', {
  keygen: file => { return file.shortPath.split('/').pop() }
})

// run all tests
Object.keys(files).forEach( function(filepath) {
  Object.keys(files[filepath]).forEach( function(testName) {
    if( !pattern || filepath.match( pattern ) )
      tape( filepath + ' ' + testName + ':', files[filepath][testName] )
  })
})
```


- `runner.sh`
```
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
node $DIR/runner.js $1 | node $DIR/node_modules/tap-spec/bin/cmd.js;
```

then from any module you can just add the `testing` module to `package.json` and change the `npm test` script to something like this: `node_modules/testing/runner.sh`, this is cool because I can refactor the testing module and the effect will be seen across all modules

the script is set up to match files ending in `Test.js` but this can obviously be modified to suit our workflow, plus there is a "pattern" option for `$2` so you can test only one file with a command such as `npm test MyFile`
