### ISSUE TITLE
circle-ci misconfigured/broken

### ISSUE THREAD

**Issue by missinglink** [pelias/api#419]
circle-ci seems not to be working properly

see https://github.com/pelias/api/pull/418

in that PR the travis tests pass and the circle ones fail; which is odd.

the error message is `TypeError: undefined is not a function`

I'm not familiar enough with circle to fix it.

Why do we use _both_ travis _and_ circle? it seems like overkill?

**Comment by dianashk** [comment]
We need circle because it's used to automatically deploy to dev and staging. So we need to figure out how to fix this.

**Comment by orangejulius** [comment]
Do we still use circle for the api? The config file is still there but it looks like there hasn't been a build in [a few months](https://circleci.com/gh/pelias/api).

**Comment by dianashk** [comment]
Since we are now going through circle-ci setup on all the repos, might be a good time to revisit this issue and close if needed.

**Comment by orangejulius** [comment]
I was able to track down the [build that failed](https://circleci.com/gh/pelias/api/228). My guess is it failed because we had [already begun requiring Node.js 4](https://github.com/pelias/api/pull/320) by that time, and circle by default used 0.12.

In any case, the recent builds have been working, and this issue is no longer relevant :tada:
