### ISSUE TITLE
Label generation / admin-lookup

### ISSUE THREAD

**Issue by dianashk** [pelias/api#454]
Searching for `Wales` results in a strange label `Powys` because geonames refers to Wales as a region whereas WOF thinks it's a macroregion. So the admin-lookup does the wrong thing and then the label generator removes name and leaves only region and that shows up wrong, even though we found the right result.

Similar situation with London now having City of Westminster in the label.

**Comment by trescube** [comment]
Trivia: https://en.wikipedia.org/wiki/Powys

**Comment by trescube** [comment]
The label generation code is confusing because is relies upon knowledge of how records are structured and that a records' `name` and most granular admin value are duplicates and will be deduplicated later.  For example, a city record for `Socorro` will have the label parts `[Socorro, Socorro, NM, USA]` that gets reduced to `Socorro, NM, USA` since the first two `Socorro`'s will be uniq'd down to 1.  

With this in mind, the region record for `Pennsylvania` results in the label parts `[Pennsylvania (name), PA (abbr), USA]`.  No reduction is done via uniq'ing so it gets an odd-looking label.  

The label generation modification for ensuring that a search for `Pennsylvania` results in the label `Pennsylvania, USA` instead of `Pennsylvania, PA, USA` is to blame here.  Specifically, the function:

```function getInitialLabel(record) {
  if ('region' === record.layer && ('geonames' === record.source || 'whosonfirst' === record.source)) {
    return [];
  }

  return [record.name];

}```

The label generation modifications done for `Pennsylvania, USA` should take into account whether the record is in US/CA.  Additionally, the label schema should use macroregion.  The code doesn't currently, so in a country with macroregions, the label will be just the `name` and `country_a`.

**Comment by trescube** [comment]
We may have to deal with suboptimal data for now, according to WOF, there are 152 regions of England:

https://whosonfirst.mapzen.com/spelunker/id/404227469/descendants/?&placetype=region

Spot-checking, a number of these appear to be cities.  For example, the other geocoder I worked on in a previous life treats Bermondsey as a city, whereas WOF treats it as a region.  If anything, [London](https://whosonfirst.mapzen.com/spelunker/id/101750367/) this should be a region, not a locality.
