### ISSUE TITLE
Respect privacy headers

### ISSUE THREAD

**Issue by dianashk** [pelias/api#460]
Stop logging requests when DO_NOT_TRACK header is sent.

**Comment by riordan** [comment]
Should respect:
* `DNT`
* `dnt`
* `do_not_track`

The [spec](https://www.ietf.org/archive/id/draft-mayer-do-not-track-00.txt) sticks to the header as `DNT` with `DNT = 1` as the official way to express opt-out, but basically the presence of `DNT` is usually enough to express opt-out.

```
5.  Header Syntax

   The Do Not Track HTTP header, "DNT", must take one of two values: "1"
   ("opt out") or "0" ("opt in").  All other values are reserved.

```

I'm concerned I haven't come across a list of who's implemented it so `DNT = 0` is on by default, so that the mere presence of the header would be insufficient to know explicit user preference. But from what I can tell, nobody does that; it's all opt-in. Just don't know for certain.

**Comment by orangejulius** [comment]
Who uses `do_not_track`?

**Comment by riordan** [comment]
Folks non-compliant with the spec. But people call it "do not track" all the time and don't know to set it as `DNT`. I'd be nice to try to respect their (improperly expressed but still pretty close) wishes as well.
