### ISSUE TITLE
Expose binary in package.json

### ISSUE THREAD

**Issue by sheerun** [pelias/api#609]
Currently it's not possible to use this package as dependency and run pelias api server with simple command. I'd suggest adding "bin" key in package.json to fix it.

**Comment by orangejulius** [comment]
Hmm, interesting. We actually don't use the versions of this repo published on NPM, although we have [plans](https://github.com/pelias/pelias/issues/323) to do so. Thanks for reporting this since we are unaware of a lot of issues when using these packages as dependencies.

But, it feels to me like we don't want to expose a binary for the API, and instead just have `npm start` do the right thing, which it already does.

Would something like `cd node_modules/pelias-api; npm start` work, or is there a case where a `pelias-api` executable that does the same thing would really be more useful?

**Comment by sheerun** [comment]
That's not ideal :) Npm suggests to never use `node_modules` directly. And Ideally pelias-api would expose express middleware I can attach to my app, no need for binary.

You could fix that by changing `main` to `app.js` instead of `index.js`.

Your `index.js` is an equivalent of `cli.js` in many node package (and they put it in bin, for easy use).

I suggest following changes:

1. Rename `index.js` to `cli.js`
2. Rename `app.js` to `index.js`
3. Add `"bin": "cli.js"` to package.json

or

1. Change `"main"` in package.json to point to `app.js`
2. Add `"bin": "index.js"` to package.json

**Comment by orangejulius** [comment]
Hi everyone. Long time no update here.

@sheerun has done a great job of outlining how to solve this issue, and we would gladly accept a pull request to do it. If someone is interested in giving it a go, we'd be happy to help you get started.

**Comment by worace** [comment]
Heads up I took a stab at adding this with https://github.com/pelias/api/pull/1180. I found I was able to get it to work with an even simpler approach of just exposing the existing `bin/start` script as the executable command for the package.

However there may be other reasons I'm not aware of why the more thorough restructuring described above is still desirable, so I'm happy to discuss that further if others have opinions on it.
