### ISSUE TITLE
Possible issue with alternate names indexing

### ISSUE THREAD

**Issue by sheerun** [pelias/api#610]
If I use `setName` or pelias document multiple times (with different key), and index it, pelias api won't return results for alternate names. For example "Breslau" is german name for "Wrocław" city of Poland, yet Pelias won't return any results for it.

My workaround is to create new record for every alternate name, but it a bad hack.

**Comment by orangejulius** [comment]
Hey @sheerun,
We definitely have an issue with this. Alt name support has a long history here and is in fact quite challenging. We had to turn it off a while ago because it lead to a lot of issues with our tests, but it's past time we revisit it.

There's quite a lot involved though, and we currently are planning on taking care of this in the last 3 months of this year. We have a ticket (https://github.com/pelias/pelias/issues/194) to track our progress, so definitely keep an eye on things there. In the next couple days I plan on writing a bit more about some of the challenges and requirements so that we can possibly start making incremental progress even sooner.

**Comment by dianashk** [comment]
We now support alt-names for admin areas via `placeholder`! Let us know if you run into any issues with that functionality. Thanks!
