### ISSUE TITLE
Inconsistent Autocomplete

### ISSUE THREAD

**Issue by missinglink** [pelias/api#69]
This UX issue is somewhat subjective, so I'll try to explain why I think it is a problem.

Consider the gif below:
![ss](http://peter.johnson.s3.amazonaws.com/unpredictable.gif)

As the amount of characters are added to the query "Hackney City Farm" we get very different results back, those results differ both in which layers the data comes from; the ratio of local/distant entries and the total amount of items returned.

For all characters up to and including "hackney " we only get administrative entries returned, I personally think this is fine with the exception of a large amount of distant or low population admin entries that appear before your first word is completely formed.

When you reach 8 characters, eg. "hackney c" you seem to get an odd mix of admin entries and places, this is also where some entries from over 6000km appear in the results.

When you type "hackney ci" you don't get any results at all? I find this behaviour very odd and it seems like a bug?

After typing "hackney cit" or more characters the correct local POI is returned.

note, to reproduce the above query bias: https://mapzen.com/pelias#loc=18,51.54503,-0.05639

cc/ @pelias/owners

**Comment by hkrishna** [comment]
This is similar to the empire state bug. As you type empire state you see
that st is analyzed as street and sta to station.. similarly, I think ci is
being analyzed as citadel or something  and since we use synonyms as one of
our token filters on name.default field this is a known problem.

I have a few solutions in mind that involves extending the synonyms
filter..

**Comment by dianashk** [comment]
Waiting on ES 2.0.0

**Comment by missinglink** [comment]
this issue was resolved by the ngrams release
