### ISSUE TITLE
Specify properties to send back in results

### ISSUE THREAD

**Issue by sevko** [pelias/api#79]
@baldur mentioned that it'd be useful to allow cherry-picking the properties returned by the API to reduce payload size. For instance, you could limit the following:

```javascript
{
    "geometry": {
        "coordinates": [
            -73.94958,
            40.6501
        ],
        "type": "Point"
    },
    "properties": {
        "admin0": "United States",
        "admin1": "New York",
        "admin2": "Kings County",
        "alpha3": "USA",
        "id": "5110302",
        "layer": "geoname",
        "name": "Brooklyn",
        "text": "Brooklyn, Kings County, New York",
        "type": "geoname"
    },
    "type": "Feature"
}
```

to

```javascript
{
    "geometry": {
        "coordinates": [
            -73.94958,
            40.6501
        ],
        "type": "Point"
    },
    "properties": {
        "admin0": "United States",
        "admin1": "New York",
        "admin2": "Kings County",
        "text": "Brooklyn, Kings County, New York",
        "type": "geoname"
    },
    "type": "Feature"
}
```

**Comment by dianashk** [comment]
This should be taken into consideration during API redesign. 

Related to pelias/pelias#42

**Comment by missinglink** [comment]
There has been a fair bit of discussion around the consumer having more control over the properties returned by API, most notably https://github.com/pelias/api/issues/101

There is certainly a tradeoff in trimming the db response in javascript as mentioned in https://github.com/pelias/api/pull/122#issuecomment-99095705

If we decide to offer this level of configuration we should do it at query-time rather than in the controller code by adding a [fields](http://www.elastic.co/guide/en/elasticsearch/reference/1.5/search-request-fields.html) params to all queries. This will give us a speed-up all the way down the stack and all the way back up again, plus the problems of selectively mapping the data to the JSON response go away.

In order to accomplish this, we would need to re-jig our queries a bit as the response body from elasticsearch for a `fields` query is different from that without.

**Comment by dianashk** [comment]
Hold off until API-redesign

**Comment by dianashk** [comment]
No longer relevant. Covered by the introduction of the `view` parameter.
