### ISSUE TITLE
Broadway doesn't get parsed correctly

### ISSUE THREAD

**Issue by kevincennis** [pelias/api#869]
Disclaimer: This is fundamentally an issue in `addressit`, and I have a [PR](https://github.com/DamonOehlman/addressit/pull/21) open there – but I wanted to get it on your radar in case you might have other/better ways of solving this, or so that you can update your `addressit` version if/when my pull request gets merged.

---

Basically, an autocomplete search for `100 Broadway Brooklyn` returns 0 results, because the address parser doesn't know `Broadway` is a street. It's a weird special case where there's no "Street" or "Road" or "Avenue" at the end.

If there's anything that you think could be done in this repo and you'd like me submit a pull request, I'd be happy to do that. Off the top of my head, it seems possible that you could add some special-cased code to `sanitizer/_text_addressit.js` to detect this and patch the `parsed_text` object.

By the way, thanks for open-sourcing pelias 👏 . It's been a great learning resource.

**Comment by orangejulius** [comment]
Hey @kevincennis,
Thanks for submitting that PR and good catch. I don't think its worth it for you to submit a PR just to patch Pelias in the meantime, because we use [Greenkeeper](http://greenkeeper.io/) and will find out about the new addressit version as soon as its available. We'll test it and roll it out as soon as we can once that happens.

Also, we'll probably be working on a major overhaul of our autocomplete endpoint in the next few months (we've been mostly focusing on the search endpoint for a while and it's time to give autocomplete some love). We're always looking to know about other cases that don't work currently. If you ran into any trouble while setting up any pelias code you've looked at, we'd also love to know about that. Cheers!

**Comment by dianashk** [comment]
Quick update: The fix is in staging now and should get rolled out to production in a few days. Thanks again @kevincennis! :star:

**Comment by orangejulius** [comment]
Hey everyone,
The new version of addressit made it to production last week, and now these queries look great:

[/v1/autocomplete?text=100 Broadway Brooklyn](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=100%20Broadway%20Brooklyn)
![screenshot from 2017-07-11 14-35-40](https://user-images.githubusercontent.com/111716/28084337-4c866ff0-6646-11e7-9bb8-0719371d8fac.png)
