### ISSUE TITLE
Duplicate result inconsistency

### ISSUE THREAD

**Issue by kevincennis** [pelias/api#872]
I have two nearly identical searches, but one uses `focus.point`:

[/v1/autocomplete?text=284%20Broadway,%20Cambridge&layers=address&boundary.country=us](http://pelias.github.io/compare/#/v1/autocomplete%3Flayers=address&boundary.country=us&text=284%20Broadway,%20Cambridge)

[/v1/autocomplete?text=284%20Broadway,%20Cambridge&layers=address&boundary.country=us&focus.point.lat=42.3601&focus.point.lon=-71.0589](http://pelias.github.io/compare/#/v1/autocomplete%3Flayers=address&boundary.country=us&focus.point.lat=42.3601&focus.point.lon=-71.0589&text=284%20Broadway,%20Cambridge)

The first query returns `us/ma/statewide:43976057cecaadf8`, and the second returns `us/ma/city_of_cambridge:9d29920532149cc0`. The latter doesn't have a `postalcode`.

I can't quite figure out why `focus.point` ends up preferring the second version – but it would be cool if the dedupe middleware could pick a winner not just by data source, but also by record completeness.

---

If this is something you think is worth tackling, I'd be happy to throw together a PR. But I might need a bit of guidance.

**Comment by dianashk** [comment]
Hey, @kevincennis! Thank you for reaching out. This is a great catch. 

Looks like the reason the one without a postalcode gets returned first is because it's ever so slightly closer to the focus point than the other one. The one without a postalcode comes back with  `"distance": 3.326` and the one with it has `"distance": 3.329`.

You are totally right about updating the deduplication middleware to prefer records that have postalcodes when both are from OA. This would probably get added [somewhere in this function](https://github.com/pelias/api/blob/master/middleware/dedupe.js#L65-L78). We would be thrilled to accept a PR for it. If you need any further support just let us know in here and we'll follow-up.

Thanks again! :wave:

**Comment by kevincennis** [comment]
Awesome, thanks for pointing me in the right direction. I'll try to get a PR together in the next couple days.
